#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 07 11:33:29 CST 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_cpu_behav -key {Behavioral:sim_1:Functional:tb_cpu} -tclbatch tb_cpu.tcl -view /media/andre/98665C09665BE712/Cinvestav/Cursos-Ene-Abr/Arquitectura de computadoras/Entrega1/tb_cpu_behav.wcfg -log simulate.log"
xsim tb_cpu_behav -key {Behavioral:sim_1:Functional:tb_cpu} -tclbatch tb_cpu.tcl -view /media/andre/98665C09665BE712/Cinvestav/Cursos-Ene-Abr/Arquitectura de computadoras/Entrega1/tb_cpu_behav.wcfg -log simulate.log

